{
    "title": "MP4电影",
    "author": "LR",
    "Headers": "PC_UA",
    "Coding_format": "UTF-8",
    "PicNeedProxy": "0",
    "homeContent":"1",
    "firstpage": "1",
    "class_url": "https://m.mp4us.com/list/{cateId}-{catePg}.html[firstPage=https://m.mp4us.com/list/{cateId}-1.html]",
    "class_name": "电视剧&动漫&纪录片&喜剧片&动作片&爱情片&科幻片&恐怖片&剧情片&战争片",
    "class_value": "10&9&8&4&1&2&3&5&7&6",
    "filterdata": {},
    "cat_mode": "1",
    "catjson_twice": "",
    "cat_arr_rule": "body&&table[width=388]",
    "cat_is_jsoup": "1",
    "cat_title": "img&&alt",
    "cat_url": "a&&href",
    "cat_pic": "img&&src",
    "cat_subtitle": "[align=center]&&Text",
    "cat_prefix": "https://m.mp4us.com/",
    "cat_suffix": "",
    "SHeaders": "User-Agent$PC_UA",
    "search_url": "https://m.mp4us.com/search/;post",
    "sea_PtBody": "show=title&tempid=1&tbname=article&mid=1&dopost=search&submit=&keyboard={wd}",
    "search_mode": "1",
    "sea_arr_rule": "body&&.post_hover",
    "sea_is_jsoup": "1",
    "sea_pic": "img&&src",
    "sea_title": "font&&Text",
    "sea_url": "a&&href",
    "sea_subtitle": "",
    "search_prefix": "https://m.mp4us.com/",
    "search_suffix": "",
    "force_play": "0",
    "play_prefix": "https://live.52sf.ga/huya/",
    "play_suffix": "#isVideo=true#",
    "play_header": "authority$ku.peizq.online#Referer$https://play.peizq.online",
    "proj_is_jsoup": "0",
    "proj_cate": "语　　言",
    "proj_year": "年　　代",
    "proj_area": "类　　别",
    "proj_actor": "演　　员　&&</p>",
    "proj_plot": "简　　介&&</p>",
    "list_arr_rule": "body&&[href*=magnet]",
    "epi_arr_rule": "a",
    "epi_is_jsoup": "1",
    "epi_title": "a&&Text",
    "epi_url": "a&&href",
    "epi_reverse": "0",
    "epiurl_prefix": "",
    "epiurl_suffix": "",
    "Anal_MacPlayer": "0",
    "ManualSniffer": "0",
    "VideoFormat": ".mp4#.m3u8#.flv",
    "VideoFilter": ".html#=http"
}